language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
install:
    - pip install -U setuptools==33.1.1
    - python bootstrap.py
    - bin/buildout
script:
    - bin/test -v1
notifications:
    email: false
